### ISSUE TITLE
What should I put on the command line argument?

### ISSUE THREAD

**Issue by tomming** [howerj/libforth#1]

**Comment by howerj** [comment]
To build, it should just be "make", to run the program there is a man page called "forth.1" which describes the possible command line arguments and gives examples. I will copy the contents of "forth.1" into a section in "readme.md" so it is clearer what to do.

As an example:

(on Linux)

>   ./forth -t forth.fth

(on Windows)

> forth.exe -t forth.fth

This will run the interpreter on the startup file, then read from stdin. You can create core files which contain the compiled code, then run the interpreter on them as well:

> ./forth -s forth.fth
> ./forth -l forth.core

Does this answer you question?

**Comment by howerj** [comment]
The documentation should be updated now, is that okay?

**Comment by tomming** [comment]
Thanks, it worked
